title: Shazia Omar
logo: /assets/img/headshot_circle.png
description: Detail-Oriented | Problem-Solver & Innovator | Committed to Continuous Learning & Collaborating to Deliver Reliable Solutions
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
